AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'lambda

  '
Globals:
  Function:
    Timeout: 300
Resources:
  lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://samtestpoc/62d9ea4ced3283e560a8024ab19b8e49
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          ENV: ${ENV}
          AWS_REGION_NAME: ${AWS_REGION_NAME}
    ArtifactStore:
      Type: S3
      Bucket: arn:aws:s3:::samtestpoc
      Prefix: lambda
    Metadata:
      SamResourceId: lambda
